const USERS = [
  { name: 'BassDrop99',     color: '#FF4500' },
  { name: 'VibezOnly',      color: '#9B59FF' },
  { name: 'Melodix_',       color: '#00C9C9' },
  { name: 'TrapQueen404',   color: '#FF69B4' },
  { name: 'SoundHunter',    color: '#1DB954' },
  { name: 'NightOwl_Beats', color: '#FF8C00' },
  { name: 'Wavvy_K',        color: '#00D4D4' },
  { name: 'ElectroSoul',    color: '#DA70D6' },
  { name: 'LoFiLover',      color: '#E8D44D' },
  { name: 'BeatMaker_Pro',  color: '#2ECC71' },
  { name: 'SubWoofer42',    color: '#FF6347' },
  { name: 'MixMaster_J',    color: '#4C8EFF' },
  { name: 'FrequencyX',     color: '#20C2AA' },
  { name: 'RhythmRider',    color: '#FF1493' },
  { name: 'SynthWave_',     color: '#8877EE' },
  { name: 'DrumLine_K',     color: '#3DCC3D' },
  { name: 'AudioPhile',     color: '#DC143C' },
  { name: 'GlitchHop_',     color: '#00FA9A' },
  { name: 'BassHead777',    color: '#FF5722' },
  { name: 'CrateDigger',    color: '#9C27B0' },
  { name: 'VinylFreak',     color: '#FF7F50' },
  { name: 'SampleKing',     color: '#29B6F6' },
  { name: 'EchoEffect_',    color: '#AEEA00' },
  { name: 'ReverbGod',      color: '#F06292' },
  { name: 'TempoTom',       color: '#1E90FF' },
  { name: 'HarmonyHive',    color: '#FFD700' },
  { name: 'PulseBeat_',     color: '#FF7043' },
  { name: 'SonicBlast',     color: '#76FF03' },
  { name: 'MelodyMaker',    color: '#CE93D8' },
  { name: 'WaveRider_X',    color: '#26C6DA' },
];

// [userIndex, message, delayMs]
const MESSAGES = [
  [0,  "ce son est incroyable omg 🔥", 800],
  [1,  "PogChamp le drop arrive !!!", 1400],
  [2,  "j'écoute Ekko Music depuis 2 ans et c'est toujours aussi bon", 2100],
  [3,  "KEKW la transition c'était quoi là 💀", 900],
  [4,  "quelqu'un connaît le nom du sample ?", 1600],
  [10, "@SoundHunter : aucune idée mais j'adore aussi", 800],
  [5,  "le mix est parfait ce soir", 1200],
  [6,  "banger detected 🚨🚨🚨", 700],
  [7,  "first time here, c'est quoi cette prod ?!", 2000],
  [2,  "@ElectroSoul : bienvenue ! c'est Ekko Music, tu vas pas regretter", 900],
  [7,  "@Melodix_ : merci ! je reste c'est sûr", 700],
  [8,  "lofi vibes supremes rn", 1300],
  [9,  "j'attendais ça depuis des semaines", 1800],
  [0,  "@BeatMaker_Pro : t'étais au courant avant tout le monde toi lol", 900],
  [9,  "@BassDrop99 : j'suis abonné à la newsletter ouais 😄", 700],
  [10, "la basse me détruit les oreilles PogChamp", 1100],
  [11, "tu mixes quoi comme soft ?", 900],
  [12, "les fréquences sont incroyablement bien placées", 2200],
  [13, "on peut acheter cette track quelque part ?", 1500],
  [14, "retrowave pur jus 🌊", 800],
  [15, "le kick est énorme wtf", 1700],
  [16, "qualité audio top comme d'hab", 1000],
  [17, "le glitch sur le pad c'était volontaire ou pas lol", 2400],
  [16, "@GlitchHop_ : clairement volontaire, c'est sa patte", 800],
  [17, "@AudioPhile : aaah ok je savais pas que c'était intentionnel", 700],
  [18, "baaaaass monter le sub 🔊", 600],
  [10, "@BassHead777 : ouais +1 on veut plus de basse", 900],
  [18, "@SubWoofer42 : t'as compris la mission frère 😂", 700],
  [19, "c'est signé sur quel label ?", 1900],
  [20, "vinyle > digital change my mind", 1300],
  [21, "@VinylFreak : les deux peuvent coexister nan ?", 1200],
  [20, "@SampleKing : non. vinyle only. point final lol", 700],
  [21, "@VinylFreak : KEKW ok ok tu gagnes", 600],
  [22, "l'écho sur cette voix chef d'oeuvre", 1100],
  [23, "reverb immense ce soir", 900],
  [22, "@ReverbGod : on est d'accord, la réverb est parfaitement dosée", 800],
  [24, "le tempo est hypnotique", 2000],
  [25, "l'harmonie avec le lead c'est parfait", 1400],
  [26, "les pulsations me donnent des frissons", 800],
  [27, "SONIC BLAST ACTIVÉ 💥", 700],
  [28, "cette mélodie restera dans ma tête toute la nuit", 1800],
  [29, "les vagues de son sont dingues", 1200],
  [28, "@WaveRider_X : exactement, c'est fait pour rester dans la tête", 900],
  [29, "@MelodyMaker : ouais c'est du génie pur", 700],
  [0,  "le drop à 2:30 j'en reviens pas", 2100],
  [1,  "c'est passé en playlist officielle Spotify ?", 1500],
  [4,  "@VibezOnly : j'ai cherché, pas encore mais ça devrait venir", 900],
  [1,  "@SoundHunter : merci pour l'info, j'espère vite !", 700],
  [2,  "Pog la montée !!", 600],
  [3,  "ce beat est une bombe", 1700],
  [4,  "sound design de malade", 900],
  [5,  "clip officiel quand ??", 1300],
  [6,  "les hi-hats sont tellement précis", 2000],
  [7,  "nouveau venu dans la communauté, incroyable ce que je découvre", 1600],
  [8,  "lo-fi à son meilleur niveau", 1100],
  [9,  "j'ai besoin de la setlist pls", 800],
  [11, "@BeatMaker_Pro : il poste la setlist sur Instagram après chaque live en général", 1000],
  [9,  "@MixMaster_J : ah ok merci je vais check ça", 700],
  [10, "sub bass goes BRRRRR", 700],
  [11, "ce mix ferait vriller n'importe quelle scène", 1900],
  [12, "les transitions sont ultra smooth", 1400],
  [13, "je veux ça en vinyl maintenant", 2200],
  [20, "@RhythmRider : +1 on signe tous une pétition pour le pressing vinyl 😂", 900],
  [13, "@VinylFreak : HAHA let's gooo", 700],
  [14, "80s synth vibes immaculées", 1000],
  [15, "la caisse claire claque FORT", 1700],
  [16, "les détails dans le mix 👌👌", 900],
  [17, "glitch effect sur la voix OP", 1800],
  [18, "besoin de plus de basse lol jamais assez", 700],
  [19, "distributeur officiel ?", 1500],
  [20, "la texture du son est incroyable", 1200],
  [21, "sample Dilla là non ? 👀", 2000],
  [19, "@SampleKing : j'entends Dilla aussi ouais, ou peut-être Madlib ?", 900],
  [21, "@CrateDigger : Madlib c'est possible ouais, les deux ont des patterns similaires", 800],
  [19, "@SampleKing : je dirais plutôt Dilla sur les swings", 700],
  [22, "cet écho me transporte dans un autre monde", 1300],
  [23, "reverb plate ou spring ?", 900],
  [22, "@ReverbGod : j'entends les deux en layering", 800],
  [23, "@EchoEffect_ : t'as raison, il y a du plate sur les voix et spring sur la guitare", 700],
  [24, "le tempo qui accelere subtilement c'est génie", 1700],
  [25, "harmonie vocale à 1:45 trop belle", 1100],
  [26, "les pulsations me font lever de ma chaise", 800],
  [27, "son qui explose les HP 💀", 600],
  [28, "cette mélodie est trop triste et trop belle à la fois", 2100],
  [29, "wave after wave de bonnes vibrations", 1400],
  [0,  "live set complet quand ?", 1800],
  [1,  "c'est du futur bass ?", 1000],
  [6,  "@VibezOnly : je dirais plutôt cinematic bass, trop organisé pour du futur bass pur", 900],
  [1,  "@Wavvy_K : ah oui tu vois bien le truc", 700],
  [2,  "Ekko Music on top ce soir !!!", 700],
  [3,  "j'achète les droits de ce beat dites-moi un prix lol", 1900],
  [4,  "la dynamique du son est impressionnante", 1300],
  [5,  "date de sortie officielle annoncée ?", 1600],
  [6,  "cette kick drum marche au MPD ou au clavier ?", 900],
  [15, "@Wavvy_K : d'après ce que j'ai vu dans une interview, MPD + clavier en combo", 1000],
  [6,  "@DrumLine_K : ah intéressant merci !", 700],
  [7,  "première écoute et déjà fan à vie", 2000],
  [2,  "@ElectroSoul : bienvenue dans la famille frère 🙌", 800],
  [8,  "lofi + house = amour", 1100],
  [9,  "setlist disponible sur Discord ?", 800],
  [10, "ma voiture va exploser demain avec ce bass", 700],
  [18, "@SubWoofer42 : lol pareil, mes vitres tremblent 😂", 900],
  [10, "@BassHead777 : on est pareils toi et moi haha", 700],
  [11, "le groove est indéniable", 1500],
  [12, "mastering parfait, où tu masters ?", 1800],
  [16, "@FrequencyX : d'après ses posts il maîtrise en interne sur Ozone", 900],
  [12, "@AudioPhile : Ozone j'aurais pas deviné mais ça s'entend", 700],
  [13, "edition limitée vinyl j'en veux une 🎵", 1200],
  [14, "synthwave qui déchire les nuages", 1000],
  [15, "pattern de batterie ultra technique", 1700],
  [16, "mix parfaitement équilibré comme toujours", 900],
  [17, "le glitch au refrain était planifié hein ?", 2100],
  [18, "montez les subwoofers s'il vous plaît 🙏", 600],
  [19, "cette track mérite un label mondial", 1400],
  [20, "le craquement du vinyl sur l'intro 🔥🔥", 1800],
  [21, "sampling game niveau dieu", 900],
  [22, "l'écho sur le piano m'a mis ko", 1600],
  [23, "reverb qui donne l'impression d'être dans une cathédrale", 1100],
  [24, "le tempo à 128 BPM c'est le sweet spot", 2000],
  [25, "les cordes sur ce drop inattendu mais parfait", 1300],
  [26, "je pulse littéralement au son de cette basse", 800],
  [27, "cette prod devrait tourner partout 💥", 700],
  [28, "mélodie qui reste gravée à vie, gg", 1900],
  [29, "les waves d'énergie ce soir c'est incroyable", 1500],
  [27, "@WaveRider_X : les waves sont réelles ce soir, je sens tout", 800],
  [29, "@SonicBlast : exactement frère, on est en syntonie totale 🌊", 700],
  [0,  "encore encore encore !!", 1000],
  [1,  "Pog ce featuring sur la voix !!!", 800],
  [3,  "@VibezOnly : c'est qui le feat d'ailleurs ? quelqu'un sait ?", 900],
  [11, "@TrapQueen404 : j'ai pas reconnu non plus, voix incroyable en tout cas", 800],
  [1,  "@MixMaster_J : +1 peu importe qui c'est le résultat est dingue", 700],
  [2,  "ça fait du bien de la vraie musique", 1700],
  [3,  "quelqu'un a le lien Soundcloud ?", 1200],
  [5,  "@TrapQueen404 : lien dans le bio Instagram normalement", 900],
  [3,  "@NightOwl_Beats : merci je check ça direct", 700],
  [4,  "les détails dans le sound design = artistique", 2000],
  [5,  "le clip est en prod apparemment 👀", 900],
  [0,  "@NightOwl_Beats : t'as une source pour le clip ?!", 800],
  [5,  "@BassDrop99 : j'ai vu une story Instagram avec une caméra 📷 dans un studio", 700],
  [0,  "@NightOwl_Beats : 👀👀 j'ai hâte", 600],
  [6,  "cette snare reverse wtf", 1400],
  [7,  "j'ai partagé à 10 personnes direct", 1100],
  [8,  "lofi dreams en écoute continue depuis 1h", 1800],
  [9,  "il faut absolument sortir ça", 700],
  [10, "120Hz sur mon casque et c'est le paradis", 1600],
  [11, "cette prod sur scène ça serait monumental", 1300],
  [7,  "@MixMaster_J : ouais imagine ça dans une grande salle avec les lumières 🤩", 900],
  [11, "@ElectroSoul : exactement c'est ce que je visualise", 700],
  [12, "la stéréo est parfaite", 900],
  [13, "vinyl pressing prévu pour quand ?", 2100],
  [14, "vibes rétro au max 🌆", 1000],
  [15, "le fill de caisse claire à 3:10 🔥", 1700],
  [24, "@DrumLine_K : ce fill est insane, changement de dynamique parfait", 900],
  [15, "@TempoTom : ouais c'est le moment que j'attendais depuis le début du track", 700],
  [16, "oreilles heureuses ce soir", 800],
  [17, "glitch minimaliste très stylé", 1500],
  [18, "toujours plus de basse never enough", 600],
  [19, "licensing pour trailer ciné ça doit péter", 1900],
  [20, "craquements vinyle dans le mix = ame de la musique", 1200],
  [21, "sample flip de génie 👑", 1400],
  [22, "delay feedback parfaitement dosé", 900],
  [23, "la reverb enveloppante waouh", 1800],
  [24, "tempo constant mais tension qui monte", 1100],
  [25, "cette harmonie avec les cuivres inattendu", 700],
  [26, "le pulse de cette basse me parle directement", 2000],
  [27, "l'intensité sonore de cette prod 🤯", 1300],
  [28, "cette mélodie triste mais belle me touche vraiment", 1600],
  [0,  "@MelodyMaker : ouais c'est l'émotion pure, rare dans l'électro", 900],
  [28, "@BassDrop99 : voilà exactement ce que je ressens, merci", 700],
  [29, "les vagues d'énergie déferlent 🌊🌊", 900],
  [0,  "besoin du WAV en téléchargement svp", 1500],
  [1,  "chat on est d'accord c'est du génie ?", 700],
  [6,  "@VibezOnly : UNANIMEMENT oui 🙌", 600],
  [14, "@VibezOnly : on vote ouiiiii", 700],
  [2,  "@VibezOnly : génie confirmé par tout le chat lol", 600],
  [2,  "musique qui transcende les genres", 1800],
  [3,  "KEKW le mec à côté de moi danse seul dans sa chambre", 1200],
  [8,  "@TrapQueen404 : lol moi aussi j'avoue 😂", 800],
  [3,  "@LoFiLover : on est tous pareils ici KEKW", 700],
  [4,  "la recherche sonore dans ce projet est hallucinante", 2000],
  [5,  "prochain EP annoncé ?", 900],
  [6,  "pattern de hi-hat ultra fluide", 1400],
  [7,  "j'ai rarement entendu une telle maîtrise du son", 1100],
  [8,  "parfait pour les longues sessions de nuit", 1800],
  [9,  "collab avec qui en rêve ?", 700],
  [25, "@BeatMaker_Pro : Ekko x FKJ ça serait une tuerie absolue", 900],
  [9,  "@HarmonyHive : OMG FKJ oui s'il vous plaît 🙏", 700],
  [4,  "@HarmonyHive : ou Ekko x Bonobo ?", 800],
  [25, "@SoundHunter : Bonobo +1 !!!", 600],
  [10, "mon caisson de basses te dit merci", 1600],
  [11, "production niveau A list", 1000],
  [12, "fréquences médiums très propres gg", 900],
  [13, "pressing limité 100 exemplaires j'en suis", 2100],
  [20, "@RhythmRider : +1 je réserve maintenant haha", 800],
  [13, "@VinylFreak : on sera en compétition alors lol", 700],
  [14, "80s mais frais comme demain", 1300],
  [15, "rudiment de batterie dans un beat électro", 1800],
  [16, "le son global est parfaitement maîtrisé", 700],
  [17, "glitch art sonore à son apogée", 1500],
  [18, "encore et encore la basse 😭", 600],
  [19, "Ekko Music en BO de film = chef d'oeuvre", 1900],
  [7,  "@CrateDigger : imagine Ekko Music dans un film de Denis Villeneuve 🤯", 1000],
  [19, "@ElectroSoul : EXACTEMENT c'est ce que j'imaginais en disant ça !!", 800],
  [7,  "@CrateDigger : la scène d'ouverture d'un Blade Runner style", 700],
  [20, "le vintage dans le digital c'est cette magie là", 1200],
  [21, "échantillons impossibles à retrouver = talent pur", 1400],
  [22, "délai et écho fusion parfaite", 900],
  [23, "reverb XXL pour une prod XXL", 1700],
  [24, "120 BPM et l'âme voyage", 1100],
  [25, "accords de piano qui enveloppent tout", 800],
  [26, "battement cardiaque synchronisé sur ce beat", 2000],
  [27, "BOOM la basse vient d'assommer le chat entier", 1300],
  [18, "@SonicBlast : lol assommé +1 😂", 700],
  [10, "@SonicBlast : je confirme je suis KO", 600],
  [28, "fin de track = larmes", 1600],
  [25, "@MelodyMaker : j'ai ressenti ça aussi, cette fin est bouleversante", 900],
  [28, "@HarmonyHive : content de ne pas être le seul 🥲", 700],
  [29, "riding the sonic wave rn 🏄", 900],
  [0,  "téléchargement gratuit ou payant ?", 1500],
  [1,  "POGGERS qualité inégalée", 700],
  [2,  "maîtrise absolue du spectre sonore", 1800],
  [3,  "LUL le voisin a frappé au mur lol", 1200],
  [0,  "@TrapQueen404 : c'est normal le son voyage à travers les murs avec cette basse 😂", 900],
  [3,  "@BassDrop99 : il peut pas comprendre, c'est son problème haha", 700],
  [4,  "chaque détail est à sa place", 2000],
  [5,  "newsletter pour les annonces ?", 900],
  [6,  "open hi hat si délicat sur ce pattern", 1400],
  [7,  "recommandé par un ami, je reviendrai", 1100],
  [8,  "cette ambiance nocturne ☁️", 1800],
  [9,  "discord link dans le chat ?", 700],
  [11, "@BeatMaker_Pro : y'a un lien dans la description normalement", 900],
  [9,  "@MixMaster_J : trouvé merci !", 600],
  [10, "les lows sont cinématographiques", 1600],
  [11, "les performances live doivent être incroyables", 1000],
  [12, "la largeur stéréo impressionnante", 900],
  [13, "numéroté et signé j'en veux une 🙌", 2200],
  [14, "futuriste et nostalgique simultanément", 1300],
  [15, "les fills sont mélodiques et pas juste techniques", 1800],
  [16, "masterclass de sound design", 700],
  [17, "les glitchs sont utilisés avec goût", 1500],
  [18, "sub qui fait vibrer les meubles 😂", 600],
  [19, "sync musique x image = potentiel énorme", 1900],
  [20, "le grain du vinyle sur une prod moderne = magie", 1100],
  [21, "samples rares + talent = Ekko Music", 1400],
  [22, "l'écho crée une profondeur incroyable", 900],
  [23, "reverb qui donne de l'espace au son", 1700],
  [24, "le tempo suspendu dans le breakdown 🤯", 1200],
  [25, "les harmonies vocales sont sublimes", 800],
  [26, "pouls de la musique = pouls de la nuit", 2000],
  [27, "son qui perce tout", 1300],
  [28, "la mélodie finale reste en tête des jours entiers", 1600],
  [29, "les vagues de ce son ne s'arrêtent jamais 🌊", 900],
  [0,  "on revient demain pour le prochain live ?", 1400],
  [5,  "@BassDrop99 : j'espère que oui, je serai là 🙋", 800],
  [14, "@BassDrop99 : toujours présent moi", 700],
  [1,  "merci Ekko Music pour cette session 🙏", 1600],
  [2,  "c'était une soirée parfaite, à bientôt tout le monde", 1200],
  [7,  "@Melodix_ : à bientôt ! ravi d'avoir découvert ça ce soir", 900],
  [2,  "@ElectroSoul : reviens quand tu veux, on est une bonne communauté ici 😊", 700],
];

(function () {
  const body = document.getElementById('chat-body');
  if (!body) return;

  let index = 0;

  function addMessage(userIndex, text) {
    const user = USERS[userIndex];
    const msg = document.createElement('div');
    msg.className = 'chat-msg';
    msg.innerHTML =
      '<span class="username" style="color:' + user.color + '">' +
      user.name + '</span>' +
      '<span class="chat-sep"> : </span>' +
      '<span class="text">' + text + '</span>';
    body.appendChild(msg);
    while (body.children.length > 60) {
      body.removeChild(body.firstChild);
    }
    body.scrollTop = body.scrollHeight;
  }

  function scheduleNext() {
    if (index >= MESSAGES.length) index = 0;
    const [userIndex, text, delay] = MESSAGES[index++];
    setTimeout(function () {
      addMessage(userIndex, text);
      scheduleNext();
    }, delay);
  }

  scheduleNext();

  // Slide chat in/out from the right depending on slide 0 visibility
  const slide0 = document.querySelector('.slide[data-theme="dark"]');
  const chat = document.getElementById('twitch-chat');
  if (slide0 && chat) {
    const observer = new MutationObserver(function () {
      if (slide0.classList.contains('active')) {
        chat.classList.remove('chat-hidden');
      } else {
        chat.classList.add('chat-hidden');
      }
    });
    observer.observe(slide0, { attributes: true, attributeFilter: ['class'] });
  }
})();
