const USERS = [
  { name: 'BassDrop99',     color: '#FF4500' },
  { name: 'VibezOnly',      color: '#9B59FF' },
  { name: 'Melodix_',       color: '#00C9C9' },
  { name: 'TrapQueen404',   color: '#FF69B4' },
  { name: 'SoundHunter',    color: '#1DB954' },
  { name: 'NightOwl_Beats', color: '#FF8C00' },
  { name: 'Wavvy_K',        color: '#00D4D4' },
  { name: 'ElectroSoul',    color: '#DA70D6' },
  { name: 'LoFiLover',      color: '#E8D44D' },
  { name: 'BeatMaker_Pro',  color: '#2ECC71' },
  { name: 'SubWoofer42',    color: '#FF6347' },
  { name: 'MixMaster_J',    color: '#4C8EFF' },
  { name: 'FrequencyX',     color: '#20C2AA' },
  { name: 'RhythmRider',    color: '#FF1493' },
  { name: 'SynthWave_',     color: '#8877EE' },
  { name: 'DrumLine_K',     color: '#3DCC3D' },
  { name: 'AudioPhile',     color: '#DC143C' },
  { name: 'GlitchHop_',     color: '#00FA9A' },
  { name: 'BassHead777',    color: '#FF5722' },
  { name: 'CrateDigger',    color: '#9C27B0' },
  { name: 'VinylFreak',     color: '#FF7F50' },
  { name: 'SampleKing',     color: '#29B6F6' },
  { name: 'EchoEffect_',    color: '#AEEA00' },
  { name: 'ReverbGod',      color: '#F06292' },
  { name: 'TempoTom',       color: '#1E90FF' },
  { name: 'HarmonyHive',    color: '#FFD700' },
  { name: 'PulseBeat_',     color: '#FF7043' },
  { name: 'SonicBlast',     color: '#76FF03' },
  { name: 'MelodyMaker',    color: '#CE93D8' },
  { name: 'WaveRider_X',    color: '#26C6DA' },
];

// [userIndex, message, delayMs]
const MESSAGES = [
  [0,  "ce son est incroyable omg 🔥", 800],
  [1,  "PogChamp le drop arrive !!!", 1400],
  [2,  "j'écoute Ekko Music depuis 2 ans et c'est toujours aussi bon", 2100],
  [3,  "KEKW la transition c'était quoi là 💀", 900],
  [4,  "quelqu'un connaît le nom du sample ?", 1600],
  [5,  "le mix est parfait ce soir", 1200],
  [6,  "banger detected 🚨🚨🚨", 700],
  [7,  "first time here, c'est quoi cette prod ?!", 2000],
  [8,  "lofi vibes supremes rn", 1300],
  [9,  "j'attendais ça depuis des semaines", 1800],
  [10, "la basse me détruit les oreilles PogChamp", 1100],
  [11, "tu mixes quoi comme soft ?", 900],
  [12, "les fréquences sont incroyablement bien placées", 2200],
  [13, "on peut acheter cette track quelque part ?", 1500],
  [14, "retrowave pur jus 🌊", 800],
  [15, "le kick est énorme wtf", 1700],
  [16, "qualité audio top comme d'hab", 1000],
  [17, "le glitch sur le pad c'était volontaire ou pas lol", 2400],
  [18, "baaaaass monter le sub 🔊", 600],
  [19, "c'est signé sur quel label ?", 1900],
  [20, "vinyle > digital change my mind", 1300],
  [21, "quel sample pack tu utilises ?", 1600],
  [22, "l'écho sur cette voix chef d'oeuvre", 1100],
  [23, "reverb immense ce soir", 900],
  [24, "le tempo est hypnotique", 2000],
  [25, "l'harmonie avec le lead c'est parfait", 1400],
  [26, "les pulsations me donnent des frissons", 800],
  [27, "SONIC BLAST ACTIVÉ 💥", 700],
  [28, "cette mélodie restera dans ma tête toute la nuit", 1800],
  [29, "les vagues de son sont dingues", 1200],
  [0,  "le drop à 2:30 j'en reviens pas", 2100],
  [1,  "c'est passé en playlist officielle Spotify ?", 1500],
  [2,  "Pog la montée !!", 600],
  [3,  "ce beat est une bombe", 1700],
  [4,  "sound design de malade", 900],
  [5,  "clip officiel quand ??", 1300],
  [6,  "les hi-hats sont tellement précis", 2000],
  [7,  "nouveau venu dans la communauté, incroyable ce que je découvre", 1600],
  [8,  "lo-fi à son meilleur niveau", 1100],
  [9,  "j'ai besoin de la setlist pls", 800],
  [10, "sub bass goes BRRRRR", 700],
  [11, "ce mix ferait vriller n'importe quelle scène", 1900],
  [12, "les transitions sont ultra smooth", 1400],
  [13, "je veux ça en vinyl maintenant", 2200],
  [14, "80s synth vibes immaculées", 1000],
  [15, "la caisse claire claque FORT", 1600],
  [16, "les détails dans le mix 👌👌", 900],
  [17, "glitch effect sur la voix OP", 1800],
  [18, "besoin de plus de basse lol jamais assez", 700],
  [19, "distributeur officiel ?", 1500],
  [20, "la texture du son est incroyable", 1200],
  [21, "sample Dilla là non ? 👀", 2000],
  [22, "cet écho me transporte dans un autre monde", 1300],
  [23, "reverb plate ou spring ?", 900],
  [24, "le tempo qui accelere subtilement c'est génie", 1700],
  [25, "harmonie vocale à 1:45 trop belle", 1100],
  [26, "les pulsations me font lever de ma chaise", 800],
  [27, "son qui explose les HP 💀", 600],
  [28, "cette mélodie est trop triste et trop belle à la fois", 2100],
  [29, "wave after wave de bonnes vibrations", 1400],
  [0,  "live set complet quand ?", 1800],
  [1,  "c'est du futur bass ?", 1000],
  [2,  "Ekko Music on top ce soir !!!", 700],
  [3,  "j'achète les droits de ce beat dites-moi un prix lol", 1900],
  [4,  "la dynamique du son est impressionnante", 1300],
  [5,  "date de sortie officielle annoncée ?", 1600],
  [6,  "cette kick drum marche au MPD ou au clavier ?", 900],
  [7,  "première écoute et déjà fan à vie", 2000],
  [8,  "lofi + house = amour", 1100],
  [9,  "setlist disponible sur Discord ?", 800],
  [10, "ma voiture va exploser demain avec ce bass", 700],
  [11, "le groove est indéniable", 1500],
  [12, "mastering parfait, où tu masters ?", 1800],
  [13, "edition limitée vinyl j'en veux une 🎵", 1200],
  [14, "synthwave qui déchire les nuages", 1000],
  [15, "pattern de batterie ultra technique", 1700],
  [16, "mix parfaitement équilibré comme toujours", 900],
  [17, "le glitch au refrain était planifié hein ?", 2100],
  [18, "montez les subwoofers s'il vous plaît 🙏", 600],
  [19, "cette track mérite un label mondial", 1400],
  [20, "le craquement du vinyl sur l'intro 🔥🔥", 1800],
  [21, "sampling game niveau dieu", 900],
  [22, "l'écho sur le piano m'a mis ko", 1600],
  [23, "reverb qui donne l'impression d'être dans une cathédrale", 1100],
  [24, "le tempo à 128 BPM c'est le sweet spot", 2000],
  [25, "les cordes sur ce drop inattendu mais parfait", 1300],
  [26, "je pulse littéralement au son de cette basse", 800],
  [27, "cette prod devrait tourner partout 💥", 700],
  [28, "mélodie qui reste gravée à vie, gg", 1900],
  [29, "les waves d'énergie ce soir c'est incroyable", 1500],
  [0,  "encore encore encore !!", 1000],
  [1,  "Pog ce featuring sur la voix !!!", 800],
  [2,  "ça fait du bien de la vraie musique", 1700],
  [3,  "quelqu'un a le lien Soundcloud ?", 1200],
  [4,  "les détails dans le sound design = artistique", 2000],
  [5,  "le clip est en prod apparemment 👀", 900],
  [6,  "cette snare reverse wtf", 1400],
  [7,  "j'ai partagé à 10 personnes direct", 1100],
  [8,  "lofi dreams en écoute continue depuis 1h", 1800],
  [9,  "il faut absolument sortir ça", 700],
  [10, "120Hz sur mon casque et c'est le paradis", 1600],
  [11, "cette prod sur scène ça serait monumental", 1300],
  [12, "la stéréo est parfaite", 900],
  [13, "vinyl pressing prévu pour quand ?", 2100],
  [14, "vibes rétro au max 🌆", 1000],
  [15, "le fill de caisse claire à 3:10 🔥", 1700],
  [16, "oreilles heureuses ce soir", 800],
  [17, "glitch minimaliste très stylé", 1500],
  [18, "toujours plus de basse never enough", 600],
  [19, "licensing pour trailer ciné ça doit péter", 1900],
  [20, "craquements vinyle dans le mix = ame de la musique", 1200],
  [21, "sample flip de génie 👑", 1400],
  [22, "delay feedback parfaitement dosé", 900],
  [23, "la reverb enveloppante waouh", 1800],
  [24, "tempo constant mais tension qui monte", 1100],
  [25, "cette harmonie avec les cuivres inattendu", 700],
  [26, "beat pulsant qui fait bouger involontairement la tête", 2000],
  [27, "blast de son qui traverse le mur", 1300],
  [28, "mélodie de fin trop émouvante", 1600],
  [29, "rider les vagues de cette prod 🌊", 900],
  [0,  "les layers de prod sont insensés", 1500],
  [1,  "Pog on vient de monter d'un ton !!", 800],
  [2,  "ça c'est de la composition sérieuse", 1200],
  [3,  "le breakdown m'a coupé la respiration", 2000],
  [4,  "tu produis depuis combien de temps ?", 1700],
  [5,  "teaser du prochain projet ?", 900],
  [6,  "cette ride cymbal si chill", 1400],
  [7,  "j'aurais dû découvrir Ekko Music bien avant", 1100],
  [8,  "lofi perfectionnisme", 1800],
  [9,  "annonce de collab prochainement ?", 700],
  [10, "basse qui me retourne l'estomac dans le bon sens", 1600],
  [11, "live à Paris quand ? 🗼", 1000],
  [12, "la précision du mixage claque", 900],
  [13, "collab vinyl avec un graphiste ça serait parfait", 2200],
  [14, "synthwave intemporelle", 1300],
  [15, "ghost notes de batterie niveau pro", 1800],
  [16, "l'oreille d'un audiophile est satisfaite", 700],
  [17, "l'effet glitch donne une texture unique à ce son", 1500],
  [18, "basse basse basse toujours plus de basse 🔊", 600],
  [19, "sync avec la scène de film ça ferait des frissons", 1900],
  [20, "texture vinyle = âme du morceau", 1100],
  [21, "flip créatif au dessus de tout", 1400],
  [22, "écho spatial magnifique", 900],
  [23, "reverb comme si on était dans une salle de concert", 1700],
  [24, "tempo hypnotique et obsessionnel", 1200],
  [25, "les voix en harmonie ont créé un frisson", 800],
  [26, "le pulse de cette basse me parle directement", 2000],
  [27, "l'intensité sonore de cette prod 🤯", 1300],
  [28, "cette mélodie triste mais belle me touche vraiment", 1600],
  [29, "les vagues d'énergie déferlent 🌊🌊", 900],
  [0,  "besoin du WAV en téléchargement svp", 1500],
  [1,  "chat on est d'accord c'est du génie ?", 700],
  [2,  "musique qui transcende les genres", 1800],
  [3,  "KEKW le mec à côté de moi danse seul dans sa chambre", 1200],
  [4,  "la recherche sonore dans ce projet est hallucinante", 2000],
  [5,  "prochain EP annoncé ?", 900],
  [6,  "pattern de hi-hat ultra fluide", 1400],
  [7,  "j'ai rarement entendu une telle maîtrise du son", 1100],
  [8,  "parfait pour les longues sessions de nuit", 1800],
  [9,  "collab avec qui en rêve ?", 700],
  [10, "mon caisson de basses te dit merci", 1600],
  [11, "production niveau A list", 1000],
  [12, "fréquences médiums très propres gg", 900],
  [13, "pressing limité 100 exemplaires j'en suis", 2100],
  [14, "80s mais frais comme demain", 1300],
  [15, "rudiment de batterie dans un beat électro", 1800],
  [16, "le son global est parfaitement maîtrisé", 700],
  [17, "glitch art sonore à son apogée", 1500],
  [18, "encore et encore la basse 😭", 600],
  [19, "Ekko Music en BO de film = chef d'oeuvre", 1900],
  [20, "le vintage dans le digital c'est cette magie là", 1200],
  [21, "échantillons impossibles à retrouver = talent pur", 1400],
  [22, "délai et écho fusion parfaite", 900],
  [23, "reverb XXL pour une prod XXL", 1700],
  [24, "120 BPM et l'âme voyage", 1100],
  [25, "accords de piano qui enveloppent tout", 800],
  [26, "battement cardiaque synchronisé sur ce beat", 2000],
  [27, "BOOM la basse vient d'assommer le chat entier", 1300],
  [28, "fin de track = larmes", 1600],
  [29, "riding the sonic wave rn 🏄", 900],
  [0,  "téléchargement gratuit ou payant ?", 1500],
  [1,  "POGGERS qualité inégalée", 700],
  [2,  "maîtrise absolue du spectre sonore", 1800],
  [3,  "LUL le voisin a frappé au mur lol", 1200],
  [4,  "chaque détail est à sa place", 2000],
  [5,  "newsletter pour les annonces ?", 900],
  [6,  "open hi hat si délicat sur ce pattern", 1400],
  [7,  "recommandé par un ami, je reviendrai", 1100],
  [8,  "cette ambiance nocturne ☁️", 1800],
  [9,  "discord link dans le chat ?", 700],
  [10, "les lows sont cinématographiques", 1600],
  [11, "les performances live doivent être incroyables", 1000],
  [12, "la largeur stéréo impressionnante", 900],
  [13, "numéroté et signé j'en veux une 🙌", 2200],
  [14, "futuriste et nostalgique simultanément", 1300],
  [15, "les fills sont mélodiques et pas juste techniques", 1800],
  [16, "masterclass de sound design", 700],
  [17, "les glitchs sont utilisés avec goût", 1500],
  [18, "sub qui fait vibrer les meubles 😂", 600],
  [19, "sync musique x image = potentiel énorme", 1900],
  [20, "le grain du vinyle sur une prod moderne = magie", 1100],
  [21, "samples rares + talent = Ekko Music", 1400],
  [22, "l'écho crée une profondeur incroyable", 900],
  [23, "reverb qui donne de l'espace au son", 1700],
  [24, "le tempo suspendu dans le breakdown 🤯", 1200],
  [25, "les harmonies vocales sont sublimes", 800],
  [26, "pouls de la musique = pouls de la nuit", 2000],
  [27, "son qui perce tout", 1300],
  [28, "la mélodie finale reste en tête des jours entiers", 1600],
  [29, "les vagues de ce son ne s'arrêtent jamais 🌊", 900],
];

(function () {
  const body = document.getElementById('chat-body');
  if (!body) return;

  let index = 0;

  function addMessage(userIndex, text) {
    const user = USERS[userIndex];
    const msg = document.createElement('div');
    msg.className = 'chat-msg';
    msg.innerHTML =
      '<span class="username" style="color:' + user.color + '">' +
      user.name + '</span>' +
      '<span class="text">' + text + '</span>';
    body.appendChild(msg);
    // keep max 60 messages
    while (body.children.length > 60) {
      body.removeChild(body.firstChild);
    }
    body.scrollTop = body.scrollHeight;
  }

  function scheduleNext() {
    if (index >= MESSAGES.length) index = 0;
    const [userIndex, text, delay] = MESSAGES[index++];
    setTimeout(function () {
      addMessage(userIndex, text);
      scheduleNext();
    }, delay);
  }

  scheduleNext();
})();
